name: Deploy Branch to GitHub Pages
# Run workflow on every push to the gh-pages branch
on:
  push:
    branches: [ gh-pages ]
    
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # Commits wwwroot to the GutHub Pages
    - name: Deploy to GitHubPages branch
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: release/wwwroot # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
