name: Deploy to GitHub Pages
# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
    
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    - name: Setup .NET 5 SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100
    # publishes Blazor project to the release-folder
    - name: Publish Blazor Client
      run: dotnet publish Client/SteadFastAssessment.Client.csproj -c Release -o release --nologo
    # changes the base-tag in index.html from '/' to 'SteadfastAssessment' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to SteadfastAssessment
      run: sed -i 's/<base href="\/" \/>/<base href="\/SteadfastAssessment\/" \/>/g' release/wwwroot/index.html
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll    
    # Commits wwwroot to the GutHub Pages
    - name: Deploy to GitHubPages branch
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: release/wwwroot # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
